test_CharSegment_V3:
	cd build && make test_CharSegment_V3.out	
test_PlateRecognition:
	cd build && make test_PlateRecognition.out
test_SVM:
	cd build && make test_SVM.out
clean:
	cd build && make clean
%:
	cd build && make $@
